version: '3'
services:
  pg:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: local
    ports:
      - '5432:5432'
