version: '3'
services:
  crabtank:
    image: postgres:15
    restart: unless-stopped
    container_name: pivot
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: local
    ports:
      - '5432:5432'
