/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SecretCreateRequestDto
 */
export interface SecretCreateRequestDto {
    /**
     * 
     * @type {string}
     * @memberof SecretCreateRequestDto
     */
    secret: string;
    /**
     * 
     * @type {Date}
     * @memberof SecretCreateRequestDto
     */
    expiresAt: Date;
    /**
     * 
     * @type {number}
     * @memberof SecretCreateRequestDto
     */
    remainingViews: number;
}

/**
 * Check if a given object implements the SecretCreateRequestDto interface.
 */
export function instanceOfSecretCreateRequestDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "secret" in value;
    isInstance = isInstance && "expiresAt" in value;
    isInstance = isInstance && "remainingViews" in value;

    return isInstance;
}

export function SecretCreateRequestDtoFromJSON(json: any): SecretCreateRequestDto {
    return SecretCreateRequestDtoFromJSONTyped(json, false);
}

export function SecretCreateRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecretCreateRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'secret': json['secret'],
        'expiresAt': (new Date(json['expiresAt'])),
        'remainingViews': json['remainingViews'],
    };
}

export function SecretCreateRequestDtoToJSON(value?: SecretCreateRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'secret': value.secret,
        'expiresAt': (value.expiresAt.toISOString()),
        'remainingViews': value.remainingViews,
    };
}

