/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SecretResponseDto
 */
export interface SecretResponseDto {
    /**
     * 
     * @type {string}
     * @memberof SecretResponseDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SecretResponseDto
     */
    secret: string;
    /**
     * 
     * @type {Date}
     * @memberof SecretResponseDto
     */
    expiresAt: Date;
    /**
     * 
     * @type {string}
     * @memberof SecretResponseDto
     */
    slug: string;
}

/**
 * Check if a given object implements the SecretResponseDto interface.
 */
export function instanceOfSecretResponseDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "secret" in value;
    isInstance = isInstance && "expiresAt" in value;
    isInstance = isInstance && "slug" in value;

    return isInstance;
}

export function SecretResponseDtoFromJSON(json: any): SecretResponseDto {
    return SecretResponseDtoFromJSONTyped(json, false);
}

export function SecretResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecretResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'secret': json['secret'],
        'expiresAt': (new Date(json['expiresAt'])),
        'slug': json['slug'],
    };
}

export function SecretResponseDtoToJSON(value?: SecretResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'secret': value.secret,
        'expiresAt': (value.expiresAt.toISOString()),
        'slug': value.slug,
    };
}

