/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoItemCreateRequestDto
 */
export interface TodoItemCreateRequestDto {
    /**
     * 
     * @type {string}
     * @memberof TodoItemCreateRequestDto
     */
    listId: string;
    /**
     * 
     * @type {string}
     * @memberof TodoItemCreateRequestDto
     */
    label: string;
}

/**
 * Check if a given object implements the TodoItemCreateRequestDto interface.
 */
export function instanceOfTodoItemCreateRequestDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "listId" in value;
    isInstance = isInstance && "label" in value;

    return isInstance;
}

export function TodoItemCreateRequestDtoFromJSON(json: any): TodoItemCreateRequestDto {
    return TodoItemCreateRequestDtoFromJSONTyped(json, false);
}

export function TodoItemCreateRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoItemCreateRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'listId': json['listId'],
        'label': json['label'],
    };
}

export function TodoItemCreateRequestDtoToJSON(value?: TodoItemCreateRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'listId': value.listId,
        'label': value.label,
    };
}

