/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoItemResponseDto
 */
export interface TodoItemResponseDto {
    /**
     * 
     * @type {string}
     * @memberof TodoItemResponseDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TodoItemResponseDto
     */
    listId: string;
    /**
     * 
     * @type {string}
     * @memberof TodoItemResponseDto
     */
    label: string;
    /**
     * 
     * @type {Date}
     * @memberof TodoItemResponseDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof TodoItemResponseDto
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof TodoItemResponseDto
     */
    deletedAt?: Date;
}

/**
 * Check if a given object implements the TodoItemResponseDto interface.
 */
export function instanceOfTodoItemResponseDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "listId" in value;
    isInstance = isInstance && "label" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function TodoItemResponseDtoFromJSON(json: any): TodoItemResponseDto {
    return TodoItemResponseDtoFromJSONTyped(json, false);
}

export function TodoItemResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoItemResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'listId': json['listId'],
        'label': json['label'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'deletedAt': !exists(json, 'deletedAt') ? undefined : (new Date(json['deletedAt'])),
    };
}

export function TodoItemResponseDtoToJSON(value?: TodoItemResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'listId': value.listId,
        'label': value.label,
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
        'deletedAt': value.deletedAt === undefined ? undefined : (value.deletedAt.toISOString()),
    };
}

