/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoListResponseDto
 */
export interface TodoListResponseDto {
    /**
     * 
     * @type {string}
     * @memberof TodoListResponseDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TodoListResponseDto
     */
    label: string;
    /**
     * 
     * @type {Date}
     * @memberof TodoListResponseDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof TodoListResponseDto
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the TodoListResponseDto interface.
 */
export function instanceOfTodoListResponseDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "label" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function TodoListResponseDtoFromJSON(json: any): TodoListResponseDto {
    return TodoListResponseDtoFromJSONTyped(json, false);
}

export function TodoListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoListResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'label': json['label'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function TodoListResponseDtoToJSON(value?: TodoListResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'label': value.label,
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
    };
}

