/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoListCreateRequestDto
 */
export interface TodoListCreateRequestDto {
    /**
     * 
     * @type {string}
     * @memberof TodoListCreateRequestDto
     */
    label: string;
}

/**
 * Check if a given object implements the TodoListCreateRequestDto interface.
 */
export function instanceOfTodoListCreateRequestDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "label" in value;

    return isInstance;
}

export function TodoListCreateRequestDtoFromJSON(json: any): TodoListCreateRequestDto {
    return TodoListCreateRequestDtoFromJSONTyped(json, false);
}

export function TodoListCreateRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoListCreateRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'label': json['label'],
    };
}

export function TodoListCreateRequestDtoToJSON(value?: TodoListCreateRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'label': value.label,
    };
}

