name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  gradle-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: ./gradlew check
